font-family = SFMono-Regular
font-size = 16
cursor-style = block
cursor-style-blink = true
background = 000000
background-opacity = 0.88
background-blur-radius = 50
foreground = FAF4EC
macos-titlebar-style = transparent
window-theme = ghostty
